### ISSUE TITLE
RimPy crashes on startup - requires complete removal of all mods to fix

### ISSUE THREAD

**Issue by jimidobson** [rimpy-custom/RimPy#107]
When running RimPy, I get a "RimPy mod manager has crashed!". The log (included) doesn't point to any specific mod.

`INFO:root:Building GUI
INFO:root:GUI generated
INFO:root:Rimworld object instantiation
INFO:root:Mod initialized: Animals Logic (oblitus.animalslogic)
INFO:root:Mod initialized: Dubs Rimatomics (dubwise.rimatomics)
INFO:root:Mod initialized: Avoid Friendly Fire (falconne.aff)
INFO:root:Mod initialized: Architect Icons (com.bymarcin.architecticons)
INFO:root:Mod initialized: Designator Shapes (merthsoft.designatorshapes)
INFO:root:Mod initialized: Smart Medicine (uuugggg.smartmedicine)
INFO:root:Mod initialized: Doors Expanded (jecrell.doorsexpanded)
INFO:root:Mod initialized: Snap Out! (weilbyte.snapout)
INFO:root:Mod initialized: Room Food (uuugggg.roomfood)
INFO:root:Mod initialized: Replace Stuff (uuugggg.replacestuff)
INFO:root:Mod initialized: Buildable Terrain v1 (buildable.terrain)
INFO:root:Mod initialized: Mod Manager (fluffy.modmanager)
INFO:root:Mod initialized: [FSF] Filth Vanishes With Rain And Time (frozensnowfox.filthvanisheswithrainandtime)
INFO:root:Mod initialized: InventoryTab (kota.inventorytab)
INFO:root:Mod initialized: Animal Gear (dylan.animalgear)
INFO:root:Mod initialized: Better Pawn Control (voult.betterpawncontrol)
INFO:root:Mod initialized: Alpha Animals (sarg.alphaanimals)
INFO:root:Mod initialized: Veinminer R1.1 (ogliss.toastehs.veinminer)
INFO:root:Mod initialized: AnimalHarvestingSpot (Continued) (mlie.animalharvestingspot)
INFO:root:Mod initialized: Reasonable Components (twistedpacifist.reasonablecomponents)
INFO:root:Mod initialized: Alpha Bees (sarg.rimbees)
INFO:root:Mod initialized: BioReactor (solaris.bioreactor)
INFO:root:Mod initialized: Combat Extended Guns (ceteam.combatextendedguns)
INFO:root:Mod initialized: Brain In a Jar (translucency.braininajar.latest)
INFO:root:Mod initialized: Recipe icons (automatic.recipeicons)
INFO:root:Mod initialized: LWM's Deep Storage (lwm.deepstorage)
INFO:root:Mod initialized: Bionic icons (automatic.bionicicons)
INFO:root:Mod initialized: Everybody Gets One (uuugggg.everybodygetsone)
INFO:root:Mod initialized: Show Draftees Weapon (targhetti.showdrafteesweapon)
INFO:root:Mod initialized: Build From Inventory (uuugggg.buildfrominventory)
INFO:root:Mod initialized: RimSaves (arandomkiwi.rimsaves)
INFO:root:Mod initialized: Vanilla Furniture Expanded (vanillaexpanded.vfecore)
INFO:root:Mod initialized: Vanilla Furniture Expanded - Medical Module (vanillaexpanded.vfemedical)
INFO:root:Mod initialized: No Random Relations (bar0th.norandomrelations)
INFO:root:Mod initialized: Pawnmorpher (tachyonite.pawnmorpherpublic)
INFO:root:Mod initialized: Ambition of the Cosmic (explodoboy.snsambitioncosmic)
INFO:root:Mod initialized: Vanilla Weapons Expanded (vanillaexpanded.vwe)
INFO:root:Mod initialized: Vanilla Apparel Expanded (vanillaexpanded.vappe)
INFO:root:Mod initialized: Vanilla Armour Expanded (vanillaexpanded.varme)
INFO:root:Mod initialized: Simple Search Bar (gguake.ui.simplesearchbar)
INFO:root:Mod initialized: Alpha Biomes (sarg.alphabiomes)
INFO:root:Mod initialized: Vanilla Furniture Expanded - Security (vanillaexpanded.vfesecurity)
INFO:root:Mod initialized: RimPy Mod Manager Database (rupal.rimpymodmanagerdatabase)
INFO:root:Mod initialized: Better ModMismatch Window (madeline.modmismatchformatter)
INFO:root:Mod initialized: Vanilla Furniture Expanded - Production (vanillaexpanded.vfeproduction)
INFO:root:Mod initialized: Vanilla Weapons Expanded - Quickdraw (vanillaexpanded.vweq)
INFO:root:Mod initialized: Save Our Ship 2 (kentington.saveourship2)
INFO:root:Mod initialized: Vanilla Fishing Expanded (vanillaexpanded.vcef)
INFO:root:Mod initialized: Combat Extended Melee (ceteam.combatextendedmelee)
INFO:root:Mod initialized: Vanilla Events Expanded (vanillaexpanded.vee)
INFO:root:Mod initialized: Vanilla Furniture Expanded - Farming (vanillaexpanded.vfefarming)
INFO:root:Mod initialized: Vanilla Furniture Expanded - Art (vanillaexpanded.vfeart)
INFO:root:Mod initialized: Vanilla Weapons Expanded - Laser (vanillaexpanded.vwel)
INFO:root:Mod initialized: CM Color Coded Mood Bar [1.1+] (crashm.colorcodedmoodbar.11)
INFO:root:Mod initialized: Harmony (brrainz.harmony)
INFO:root:Mod initialized: No Job Authors (doug.nojobauthors)
INFO:root:Mod initialized: De-generalize Work (alias.degeneralizework)
INFO:root:Mod initialized: Various Space Ship Chunk (Continued) (mlie.variousspaceshipchunk)
INFO:root:Mod initialized: Vanilla Textures Expanded (vanillaexpanded.vtexe)
INFO:root:Mod initialized: Animal Medical Bed (neceros.animalmedicalbed)
INFO:root:Mod initialized: Bulk Stonecutting (fuglypump.bulkstonecutting)
INFO:root:Mod initialized: Stabilize (linkolas.stabilize)
INFO:root:Mod initialized: Vanilla Expanded Framework (oskarpotocki.vanillafactionsexpanded.core)
INFO:root:Mod initialized: Vanilla Factions Expanded - Medieval (oskarpotocki.vanillafactionsexpanded.medievalmodule)
INFO:root:Mod initialized: Vanilla Furniture Expanded - Spacer Module (vanillaexpanded.vfespacer)
INFO:root:Mod initialized: Project RimFactory Revived (spdskatr.projectrimfactory)
INFO:root:Mod initialized: Cybernetic Organism and Neural Network (kikohi.cybernetic)
INFO:root:Mod initialized: Advanced Biomes (Continued) (mlie.advancedbiomes)
INFO:root:Mod initialized: Vanilla Factions Expanded - Settlers (oskarpotocki.vanillafactionsexpanded.settlersmodule)
INFO:root:Mod initialized: Prepare Moderately (lakuna.preparemoderately)
INFO:root:Mod initialized: Bulk Smelting (neceros.bulksmelting)
INFO:root:Mod initialized: Vanilla Furniture Expanded - Power (vanillaexpanded.vfepower)
INFO:root:Mod initialized: Desire Paths (fluffy.desirepaths)
INFO:root:Mod initialized: What's Missing? (revolus.whatsmissing)
INFO:root:Mod initialized: Command Palette (fluffy.commandpalette)
INFO:root:Mod initialized: Vanilla Furniture Expanded - Props and Decor (vanillaexpanded.vfepropsanddecor)
INFO:root:Mod initialized: Animals are fun (revolus.animalsarefun)
INFO:root:Mod initialized: Vanilla Cooking Expanded (vanillaexpanded.vcooke)
INFO:root:Mod initialized: Vanilla Plants Expanded (vanillaexpanded.vplantse)
INFO:root:Mod initialized: Vanilla Cooking Expanded - Stews (vanillaexpanded.vcookestews)
INFO:root:Mod initialized: Vanilla Storytellers Expanded - Perry Persistent (vse.perrypersistent)
INFO:root:Mod initialized: Vanilla Factions Expanded - Insectoids (oskarpotocki.vfe.insectoid)
INFO:root:Mod initialized: Cybernetic Warfare and Special Weapons (Continued) (mlie.cyberneticwarfare)
INFO:root:Mod initialized: Vanilla Cooking Expanded - Sushi (vanillaexpanded.vcookesushi)
INFO:root:Mod initialized: Alpha Ships (sarg.alphaships)
INFO:root:Mod initialized: Animal Discovery (hatena.animaldiscovery)
INFO:root:Mod initialized: Vanilla Brewing Expanded (vanillaexpanded.vbrewe)
INFO:root:Mod initialized: Vanilla Books Expanded (vanillaexpanded.vbookse)
INFO:root:Mod initialized: Vanilla Weapons Expanded - Grenades (vanillaexpanded.vweg)
INFO:root:Mod initialized: Ultratech: Altered Carbon Remastered (hlx.ultratechalteredcarbon)
INFO:root:Mod initialized: Smarter Construction (dhultgren.smarterconstruction)
INFO:root:Mod initialized: Anima Gear (xrushha.animagear)
INFO:root:Mod initialized: Pawnmorpher Insects (tachyonite.pawnmorpher.insects)
INFO:root:Mod initialized: Vanilla Factions Expanded - Vikings (oskarpotocki.vfe.vikings)
INFO:root:Mod initialized: Vanilla Storytellers Expanded - Freya Fierce (vse.freyafierce)
INFO:root:Mod initialized: Vanilla Storytellers Expanded - Igor Invader (vse.igorinvader)
INFO:root:Mod initialized: Vanilla Expanded - Royalty Patches (oskarpotocki.vanillaexpanded.royaltypatches)
INFO:root:Mod initialized: Better Transhumanists (co.uk.epicguru.bettertranshumanists)
INFO:root:Mod initialized: Vanilla Brewing Expanded - Coffees and Teas (vanillaexpanded.vbrewecandt)
INFO:root:Mod initialized: Vanilla Factions Expanded - Mechanoids (oskarpotocki.vfe.mechanoid)
INFO:root:Mod initialized: Vanilla Weapons Expanded - Heavy Weapons (vanillaexpanded.vwehw)
INFO:root:Mod initialized: Anima Animals (xrushha.animaanimals)
INFO:root:Mod initialized: Bradson's Main Button Icons for VE Textures (bs.mbifvte)
INFO:root:Mod initialized: Callouts (captainmuscles.callouts)
INFO:root:Mod initialized: Almost There! (roolo.almostthere)
INFO:root:Mod initialized: Do Your F****** Research (captainmuscles.prioritizeresearch)
INFO:root:Mod initialized: Vanilla Weapons Expanded - Coilguns (vanillaexpanded.vwec)
INFO:root:Mod initialized: Smarter Deconstruction and Mining (legodude17.smartdecon)
INFO:root:Mod initialized: Functional Room (miyamiya.functionalroom.latest)
INFO:root:Mod initialized: Quality Colors (legodude17.qualcolor)
INFO:root:Mod initialized: EvolvedOrgansRedux (statistno1.evolvedorgansredux)
INFO:root:Mod initialized: Farming Hysteresis (ilyvion.farminghysteresis)
INFO:root:Mod initialized: Vanilla Social Interactions Expanded (vanillaexpanded.vanillasocialinteractionsexpanded)
INFO:root:Mod initialized: Vanilla Storytellers Expanded - Oskar Obnoxious (vse.oskarobnoxious)
INFO:root:Mod initialized: Callouts Extended! (nowano.calloutextension)
INFO:root:Mod initialized: Vanilla Weapons Expanded - Frontier (vanillaexpanded.vweft)
INFO:root:Mod initialized: Vanilla Weapons Expanded - Non-Lethal (vanillaexpanded.vwenl)
INFO:root:Mod initialized: Vanilla Weapons Expanded - Tribal (vanillaexpanded.vwetb)
INFO:root:Mod initialized: Vanilla Storytellers Expanded - Diego Industrial (vse.diegoindustrial)
INFO:root:Mod initialized: Vanilla Storytellers Expanded - Maynard Medieval (vse.maynardmedieval)
INFO:root:Mod initialized: Vanilla Storytellers Expanded - Neron Neolithic (vse.neronneolithic)
INFO:root:Mod initialized: Vanilla Fishing Expanded - Fishing Treasures AddOn (vanillaexpanded.vcefaddon)
INFO:root:Mod initialized: Combat Bionics (freefolk.combatbionics)
INFO:root:Mod initialized: No Lazy Doctors (jbloodthorn.nolazydoctors)
INFO:root:Mod initialized: Anima Animals - Community Pack (xrushha.animaanimalscommunitypack)
INFO:root:Mod initialized: Canned Food (Continued) (mlie.cannedfood)
INFO:root:Mod initialized: Vanilla Ideology Expanded - Icons and Symbols (vanillaexpanded.ideo.iconsandsymbols)
INFO:root:Mod initialized: [FSF] Better Ancient Complex Loot (frozensnowfox.betterancientcomplexloot)
INFO:root:Mod initialized: Vanilla Ideology Expanded - Relics and Artifacts (vanillaexpanded.ideo.relicsandartifacts)
INFO:root:Mod initialized: Cosmos+ (dimonsever000.cosmosreborn.specific)
INFO:root:Mod initialized: Vanilla Expanded - Ideology Patches (oskarpotocki.vanillaexpanded.ideologypatches)
INFO:root:Mod initialized: Quality Overlay (telardo.qualityoverlay)
INFO:root:Mod initialized: Architect Expanded - Fences (Continued) (mlie.architectexpandedfences)
INFO:root:Mod initialized: Signs and Comments (dark.signs)
INFO:root:Mod initialized: Pawnmorpher Transhumanist (takel.pawnmorphertranshumanist)
INFO:root:Mod initialized: Vanilla Furniture Expanded - Architect (vanillaexpanded.vfearchitect)
INFO:root:Mod initialized: Smart Farming (owlchemist.smartfarming)
INFO:root:Mod initialized: Vanilla Ideology Expanded - Memes and Structures (vanillaexpanded.vmemese)
INFO:root:Mod initialized: Vanilla Factions Expanded - Ancients (vanillaexpanded.vfea)
INFO:root:Mod initialized: Vanilla Ideology Expanded - Anima Theme (vanillaexpanded.vieat)
INFO:root:Mod initialized: Vanilla Outposts Expanded (vanillaexpanded.outposts)
INFO:root:Mod initialized: Vanilla Ideology Expanded - Dryads (vanillaexpanded.ideo.dryads)
INFO:root:Mod initialized: Vanilla Factions Expanded - Pirates (oskarpotocki.vfe.pirates)
INFO:root:Mod initialized: Vanilla Storytellers Expanded - Winston Waves (vanillastorytellersexpanded.winstonwave)
INFO:root:Mod initialized: Vanilla Backgrounds Expanded (vanillaexpanded.backgrounds)
INFO:root:Mod initialized: Vanilla Factions Expanded - Classical (oskarpotocki.vfe.classical)
INFO:root:Mod initialized: Vanilla Chemfuel Expanded (vanillaexpanded.vchemfuele)
INFO:root:Mod initialized: Vanilla Genetics Expanded (vanillaexpanded.vgeneticse)
INFO:root:Mod initialized: Vanilla Genetics Expanded - More Lab Stuff (vanillaexpanded.vgeneticsemorelabstuff)
INFO:root:Mod initialized: Vanilla Persona Weapons Expanded (vanillaexpanded.vpersonaweaponse)
INFO:root:Mod initialized: Vanilla Base Generation Expanded (vanillaexpanded.basegeneration)
INFO:root:Mod initialized: Vanilla Psycasts Expanded (vanillaexpanded.vpsycastse)
INFO:root:Mod initialized: Dragon Genetics (hol.dragongenetics)
INFO:root:Mod initialized: Cook Carefully (8z.cookcarefully)
INFO:root:Mod initialized: HologramsAndProjectors (vesper.hologramsandprojectors)
INFO:root:Mod initialized: Questionable Ethics Enhanced (Continued) (mlie.questionableethicsenhanced)
INFO:root:Mod initialized: Vanilla Skills Expanded (vanillaexpanded.skills)
INFO:root:Mod initialized: Vanilla Backstories Expanded (vanillaexpanded.vanillabackstoriesexpanded)
INFO:root:Mod initialized: Research Reinvented: Stepping Stones (petetimessix.researchreinvented.steppingstones)
INFO:root:Mod initialized: Research Reinvented (petetimessix.researchreinvented)
INFO:root:Mod initialized: Appliances Expanded (scpchemfuel.appliances)
INFO:root:Mod initialized: Vanilla Helixien Gas Expanded (vanillaexpanded.helixiengas)
INFO:root:Mod initialized: Biotech Expansion - Mammalia (biotexpans.mammalia)
INFO:root:Mod initialized: RimFridge Updated (rimfridge.kv.rw)
INFO:root:Mod initialized: Biotech Genes Elongated - Horns (mrkociak.biotechmorehorns)
INFO:root:Mod initialized: Go the F*** to Sleep - Forked (khorbos.gotosleep)
INFO:root:Mod initialized: RimNauts 2 (sindre0830.rimnauts2)
INFO:root:Mod initialized: Vanilla Races Expanded - Saurid (vanillaracesexpanded.saurid)
INFO:root:Mod initialized: Biotech Cloning (dark.cloning)
INFO:root:Mod initialized: Biotech Expansion - Mythic (biotexpans.mythic)
INFO:root:Mod initialized: Biotech Expansion - Core (biotexpans.core)
INFO:root:Mod initialized: Integrated Genes (turnovus.biotech.integratedgenes)
INFO:root:Mod initialized: Gene Ripper (danielwedemeyer.generipper)
INFO:root:Mod initialized: Gene Trader (tac.genetrader)
INFO:root:Mod initialized: Simple FX: Vapor (owlchemist.simplefx.vapor)
INFO:root:Mod initialized: S.T.A.L.K.E.R. - Combat Medicine (harkon.stalker.combatmedicine)
INFO:root:Mod initialized: Simple FX: Splashes (owlchemist.simplefx.splashes)
INFO:root:Mod initialized: Alpha Genes (sarg.alphagenes)
INFO:root:Mod initialized: Biotech - Avali (biotech.avali)
INFO:root:Mod initialized: Blueprints (fluffy.blueprints)
INFO:root:Mod initialized: Animal Tab (fluffy.animaltab)
INFO:root:Mod initialized: Colony Manager (fluffy.colonymanager)
INFO:root:Mod initialized: Area Unlocker (fluffy.areaunlocker)
INFO:root:Mod initialized: Work Tab (fluffy.worktab)
INFO:root:Mod initialized: Apparello 2 (shinzy.apparello)
INFO:root:Mod initialized: Achtung! (brrainz.achtung)
INFO:root:Mod initialized: Defensive Positions (unlimitedhugs.defensivepositions)
INFO:root:Mod initialized: Allow Tool (unlimitedhugs.allowtool)
INFO:root:Mod initialized: Call of Cthulhu - Factions (rimofmadness.callofcthulhu.factions)
INFO:root:Mod initialized: Call of Cthulhu - Cosmic Horrors (rimofmadness.callofcthulhucosmichorrors)
INFO:root:Mod initialized: Call of Cthulhu - Cults (rimofmadness.callofcthulhucults)
INFO:root:Mod initialized: HugsLib (unlimitedhugs.hugslib)
INFO:root:Mod initialized: Dubs Rimkit (dubwise.dubsrimkit)
INFO:root:Mod initialized: Dubs Skylights (dubwise.dubsskylights)
INFO:root:Mod initialized: Dubs Bad Hygiene (dubwise.dubsbadhygiene)
INFO:root:Mod initialized: Humanoid Alien Races (erdelf.humanoidalienraces)
INFO:root:Mod initialized: High Tech Laboratory Facilities (pravus109.highhtechhlaboratoryhfacilities)
INFO:root:Mod initialized: CleaningArea (hatti.cleaningarea)
INFO:root:Mod initialized: Call of Cthulhu - Elder Things (rimofmadness.callofcthulhu.elderthings)
INFO:root:Mod initialized: Better Workbench Management (falconne.bwm)
INFO:root:Mod initialized: H.P. Lovecraft Storyteller (rimofmadness.hplovecraft)
INFO:root:Mod initialized: Heat Map (falconne.heatmap)
INFO:root:Mod initialized: Cybernetic Storm (elstrages.cyberneticstorm)
INFO:root:Mod initialized: Biotech [Official DLC] (ludeon.rimworld.biotech)
INFO:root:Mod initialized: Core (ludeon.rimworld)
INFO:root:Mod initialized: Ideology [Official DLC] (ludeon.rimworld.ideology)
INFO:root:Mod initialized: Royalty [Official DLC] (ludeon.rimworld.royalty)
INFO:root:ModsConfig.xml content:

ludeon.rimworld
ludeon.rimworld.royalty
ludeon.rimworld.ideology
ludeon.rimworld.biotech

INFO:root:Rimworld object instantiation completed
INFO:root:Game version: 1.4.3563 rev533
INFO:root:Game folder: D:\SteamLibrary\steamapps\common\RimWorld
INFO:root:Configs folder: C:\Users\User\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config
INFO:root:Steam mods folder: D:\SteamLibrary\steamapps\workshop\content\294100
INFO:root:Local mods folder: D:\SteamLibrary\steamapps\common\RimWorld\Mods
CRITICAL:root:Exception
Traceback (most recent call last):
  File "D:\RimPy_Windows\rimpy.py", line 5986, in <module>
  File "D:\RimPy_Windows\rimpy.py", line 5972, in main
  File "D:\RimPy_Windows\rimpy.py", line 2662, in __init__
TypeError: argument of type 'int' is not iterable
`

Note that while the crash seems to occur checking the local mods folder, I do not have any local mods. The folder is empty, save for the "mods go here" text file which is unchanged from when I installed the game.

**Comment by rimpy-custom** [comment]
Delete folder with RimPy and reinstall it

**Comment by lmgginspace** [comment]
Same issue, and that fix doesn't work for me:
Here is my log:

```
INFO:root:Building GUI
INFO:root:GUI generated
INFO:root:Rimworld object instantiation
INFO:root:Rimworld object instantiation completed
INFO:root:Game version: 1.2
INFO:root:Game folder: ['D:\\SteamLibrary\\steamapps\\common\\RimWorld']
INFO:root:Configs folder: ['C:\\Users\\LUIS MIGUEL\\AppData\\LocalLow\\Ludeon Studios\\RimWorld by Ludeon Studios\\Config']
INFO:root:Steam mods folder: ['D:\\SteamLibrary\\steamapps\\workshop\\content\\294100']
INFO:root:Local mods folder: ['D:\\SteamLibrary\\steamapps\\common\\RimWorld\\Mods']
INFO:root:RimPy Mod Manager v. 1.2.6.28
CRITICAL:root:Exception
Traceback (most recent call last):
  File "D:\PROGRA~1\RIMPY_~1.28\rimpy.py", line 6597, in <module>
  File "D:\PROGRA~1\RIMPY_~1.28\rimpy.py", line 6577, in main
  File "D:\PROGRA~1\RIMPY_~1.28\rimpy.py", line 2964, in __init__
  File "D:\PROGRA~1\RIMPY_~1.28\rimpy.py", line 5939, in loadTheme
ValueError: invalid literal for int() with base 10: "['0']"
```

**Comment by ivellioscolin** [comment]
It's probably due to your mod directory name ['0'] can't be converted to steam workshop ID.

**Comment by ALE199** [comment]
Happends to me too, and don't know why
