### ISSUE TITLE
Crash on Linux while updating mods

### ISSUE THREAD

**Issue by stasalcatraz** [rimpy-custom/RimPy#126]
Application crashes when I'm trying to check for updates for selected active mods. Log in  Console log:

```
alcatraz@alcatraz:~/games/RimPy$ ./RimPy.sh 
Sandboxing disabled by user.
1.7421973509999589
js: Uncaught ReferenceError: qt is not defined
js: Failed to report error: ReportError() was called without an error to report.
js: Uncaught TypeError: Cannot read property 'lastChild' of undefined
js: Failed to report error: ReportError() was called without an error to report.
js: Uncaught TypeError: Cannot read property 'parentElement' of null
QCoreApplication::exec: The event loop is already running
Release of profile requested but WebEnginePage still not deleted. Expect troubles !
/home/alcatraz/games/RimPy/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
./RimPy.sh: строка 2: 43581 Ошибка сегментирования                   (стек памяти сброшен на диск) LD_PRELOAD="libpcre.so.3:$LD_PRELOAD" ./RimPy
```
Crash log:

```
INFO:root:Building GUI
INFO:root:GUI generated
INFO:root:Rimworld object instantiation
INFO:root:Mod initialized: Alpha Biomes (sarg.alphabiomes)
INFO:root:Mod initialized: [KV] Faction Control (factioncontrol.kv.rw)
INFO:root:Mod initialized: Moody (giantspacehamster.moody)
INFO:root:Mod initialized: Rah's Vanilla Turrets Expansion (rah.rvte)
INFO:root:Mod initialized: Rimefeller (dubwise.rimefeller)
INFO:root:Mod initialized: Visual Exceptions (brrainz.visualexceptions)
INFO:root:Mod initialized: Giddy-up! Mechanoids (roolo.giddyupmechanoids)
INFO:root:Mod initialized: VGP Garden Dyes (dismarzero.vgp.vgpgardendyes)
INFO:root:Mod initialized: Prepare Moderately (lakuna.preparemoderately)
INFO:root:Mod initialized: Miscellaneous 'CORE' (haplo.miscellaneous.core)
INFO:root:Mod initialized: Settlement Inventory (nmeijer.settlementinventory)
INFO:root:Mod initialized: Lulu's Scrap Anything (loonyladle.rimworld.scrapanything)
INFO:root:Mod initialized: Idle Power Consumption (sladki.idlepowerconsumption)
INFO:root:Mod initialized: Mamuffalo (dismarzero.vgp.mamuffalo)
INFO:root:Mod initialized: VGP Garden Fabrics (dismarzero.vgp.vgpgardenfabrics)
INFO:root:Mod initialized: Tech Advancing (ghxx.techadvancing)
INFO:root:Mod initialized: Electric Stonecutting Table (cocaine.electricstonecuttingtable)
INFO:root:Mod initialized: Misc. Robots++ (alaestor.miscrobots.plusplus)
INFO:root:Mod initialized: VGP Three Sisters Plants (dismarzero.vgp.vgpthreesistersplants)
INFO:root:Mod initialized: ModSync Ninja (historicthzuyasmihandhkiame201.modsynchninja)
INFO:root:Mod initialized: VGP Garden Tools (dismarzero.vgp.vgpgardentools)
INFO:root:Mod initialized: What the hack?! (roolo.whatthehack)
INFO:root:Mod initialized: Rah's Bionics and Surgery Expansion (rah.rbse)
INFO:root:Mod initialized: VGP Garden Medicine (dismarzero.vgp.vgpgardenmedicine)
INFO:root:Mod initialized: Alpha Animals (sarg.alphaanimals)
INFO:root:Mod initialized: Map Reroll (unlimitedhugs.mapreroll)
INFO:root:Mod initialized: Misc. Robots (haplo.miscellaneous.robots)
INFO:root:Mod initialized: AdvHydroponics (dar2.advhydro)
INFO:root:Mod initialized: [SYR] Universal Fermenter (syrchalis.universalfermenter)
INFO:root:Mod initialized: Misc. Training (haplo.miscellaneous.training)
INFO:root:Mod initialized: Advanced Cultivation (gasch.advancedcultivation_copy)
INFO:root:Mod initialized: Dubs Rimatomics (dubwise.rimatomics)
INFO:root:Mod initialized: Pygmy muffalo (dismarzero.vgp.pygmymuffalo)
INFO:root:Mod initialized: Giddy-up! Ride and Roll (roolo.giddyuprideandroll)
INFO:root:Mod initialized: VGP Garden Dyes Expanded (dismarzero.vgp.vgpgardendyesexpanded)
INFO:root:Mod initialized: Medical Dissection (heremeus.medicaldissection)
INFO:root:Mod initialized: Misc. MapGen FactionBase (haplo.miscellaneous.mapgenfactionbase)
INFO:root:Mod initialized: VGP Garden Fabrics Simplified (dismarzero.vgp.vgpgardenfabricssimplified)
INFO:root:Mod initialized: Vanilla Expanded Framework (oskarpotocki.vanillafactionsexpanded.core)
INFO:root:Mod initialized: Z-Levels Beta (zlevels1.1)
INFO:root:Mod initialized: Defensive Machine Gun Turret Pack (sumghai.defensivemachinegunturretpack)
INFO:root:Mod initialized: Prepare Landing (neitsa.preparelanding)
INFO:root:Mod initialized: [KV] Configurable Maps (configurablemaps.kv.rw)
INFO:root:Mod initialized: CuproPanda's Drinks (dismarzero.vgp.cupropandasdrinks)
INFO:root:Mod initialized: RimHUD (jaxe.rimhud)
INFO:root:Mod initialized: Giddy-up! Core (roolo.giddyupcore)
INFO:root:Mod initialized: Allow Tool - Instant Haul (doug.allowtool.instanthaul)
INFO:root:Mod initialized: Misc. Incidents (haplo.miscellaneous.incidents)
INFO:root:Mod initialized: Lulu's Bones and Chitin (loonyladle.rimworld.bones)
INFO:root:Mod initialized: VGP Vegetable Garden (dismarzero.vgp.vgpvegetablegarden)
INFO:root:Mod initialized: VGP Soylent Production (dismarzero.vgp.vgpsoylentproduction)
INFO:root:Mod initialized: Industrial Rollers (historic.industrialrollers)
INFO:root:Mod initialized: VGP More Veggies (dismarzero.vgp.vgpmoreveggies)
INFO:root:Mod initialized: Hospitality (orion.hospitality)
INFO:root:Mod initialized: Lulu's Vanilla Surgery Expansion (loonyladle.rimworld.vanillasurgeryexpansion)
INFO:root:Mod initialized: Children and Pregnancy (children.and.pregnancy)
INFO:root:Mod initialized: RimFortress: Dwarven Plants (dismarzero.vgp.rimfortressdwarvenplants)
INFO:root:Mod initialized: PowerSwitch (haplo.powerswitch)
INFO:root:Mod initialized: HugsLib (unlimitedhugs.hugslib)
INFO:root:Mod initialized: Giddy-up! Caravan (roolo.giddyupcaravan)
INFO:root:Mod initialized: ModSync RW (modsyncrw.kv.rw)
INFO:root:Mod initialized: Giddy-up! Battle Mounts (roolo.giddyupbattlemounts)
INFO:root:Mod initialized: [KV] Impassable Map Maker (impassablemapmaker.kv.rw)
INFO:root:Mod initialized: Kitchen Counter and Shelves (dismarzero.vgp.kitchencounterandshelves)
INFO:root:Mod initialized: Harmony (brrainz.harmony)
INFO:root:Mod initialized: Misc. Bees'n'Honey (haplo.miscellaneous.beesnhoney)
INFO:root:Mod initialized: VGP Garden Canning (dismarzero.vgp.vgpgardencanning)
INFO:root:Mod initialized: VGP Xtra Trees and Flowers (dismarzero.vgp.xtratreesandflowers)
INFO:root:Mod initialized: Misc. MapGenerator (haplo.miscellaneous.mapgenerator)
INFO:root:Mod initialized: Storage Tweaks (sladki.storagetweaks)
INFO:root:Mod initialized: VGP Garden Drinks UF (dismarzero.vgp.vgpgardendrinksuf)
INFO:root:Mod initialized: EdB Prepare Carefully (edb.preparecarefully)
INFO:root:Mod initialized: MedPod (sumghai.medpod)
INFO:root:Mod initialized: Misc. MAI (haplo.miscellaneous.mai)
INFO:root:Mod initialized: [KV] RimFridge (rimfridge.kv.rw)
INFO:root:Mod initialized: Misc. Endgame (haplo.miscellaneous.endgame)
INFO:root:Mod initialized: Allow Tool (unlimitedhugs.allowtool)
INFO:root:Mod initialized: Smoked meat (dismarzero.vgp.smokedmeat)
INFO:root:Mod initialized: [KV] Trading Spot (tradingspot.kv.rw)
INFO:root:Mod initialized: Misc. Weapon Repair (haplo.miscellaneous.weaponrepair)
INFO:root:Mod initialized: Misc. TurretBase, Objects (haplo.miscellaneous.turretbaseandobjects)
INFO:root:Mod initialized: VGP Garden Resources (dismarzero.vgp.vgpgardenresources)
INFO:root:Mod initialized: Replimat (sumghai.replimat)
INFO:root:Mod initialized: Interaction Bubbles (jaxe.bubbles)
INFO:root:Mod initialized: Carousel (zetrith.carousel)
INFO:root:Mod initialized: HolyWasher (sma342thblacharnia906.holywasher)
INFO:root:Mod initialized: Misc. MapGen Xtension 'Urban Biome' (haplo.miscellaneous.mapgenerator.urban)
INFO:root:Mod initialized: Simple sidearms (petetimessix.simplesidearms)
INFO:root:Mod initialized: Lulu's More Surgeries (loonyladle.rimworld.moresurgeries)
INFO:root:Mod initialized: Core (ludeon.rimworld)
INFO:root:Mod initialized: Ideology [Official DLC] (ludeon.rimworld.ideology)
INFO:root:Mod initialized: Royalty [Official DLC] (ludeon.rimworld.royalty)
INFO:root:ModsConfig.xml content:

brrainz.harmony
ludeon.rimworld
ludeon.rimworld.royalty
ludeon.rimworld.ideology
unlimitedhugs.hugslib
dar2.advhydro
gasch.advancedcultivation_copy
sumghai.replimat
oskarpotocki.vanillafactionsexpanded.core
sarg.alphaanimals
zetrith.carousel
dubwise.rimatomics
edb.preparecarefully
cocaine.electricstonecuttingtable
roolo.whatthehack
roolo.giddyupcore
roolo.giddyupbattlemounts
roolo.giddyupcaravan
roolo.giddyupmechanoids
roolo.giddyuprideandroll
orion.hospitality
sladki.idlepowerconsumption
historic.industrialrollers
dismarzero.vgp.kitchencounterandshelves
dismarzero.vgp.mamuffalo
unlimitedhugs.mapreroll
sumghai.medpod
heremeus.medicaldissection
haplo.miscellaneous.core
haplo.miscellaneous.beesnhoney
haplo.miscellaneous.endgame
haplo.miscellaneous.incidents
haplo.miscellaneous.mai
haplo.miscellaneous.mapgenerator
haplo.miscellaneous.mapgenfactionbase
haplo.miscellaneous.mapgenerator.urban
haplo.miscellaneous.robots
alaestor.miscrobots.plusplus
haplo.miscellaneous.training
haplo.miscellaneous.turretbaseandobjects
haplo.miscellaneous.weaponrepair
modsyncrw.kv.rw
giantspacehamster.moody
haplo.powerswitch
neitsa.preparelanding
lakuna.preparemoderately
dismarzero.vgp.pygmymuffalo
rah.rbse
rah.rvte
dismarzero.vgp.rimfortressdwarvenplants
jaxe.rimhud
dubwise.rimefeller
nmeijer.settlementinventory
petetimessix.simplesidearms
dismarzero.vgp.smokedmeat
sladki.storagetweaks
ghxx.techadvancing
syrchalis.universalfermenter
dismarzero.vgp.cupropandasdrinks
dismarzero.vgp.vgpvegetablegarden
dismarzero.vgp.vgpgardencanning
dismarzero.vgp.vgpgardendrinksuf
dismarzero.vgp.vgpgardendyes
dismarzero.vgp.vgpgardendyesexpanded
dismarzero.vgp.vgpgardenfabrics
dismarzero.vgp.vgpgardenmedicine
dismarzero.vgp.vgpgardenresources
dismarzero.vgp.vgpgardentools
dismarzero.vgp.vgpmoreveggies
dismarzero.vgp.vgpsoylentproduction
dismarzero.vgp.vgpthreesistersplants
dismarzero.vgp.xtratreesandflowers
factioncontrol.kv.rw
impassablemapmaker.kv.rw
rimfridge.kv.rw
tradingspot.kv.rw

INFO:root:Rimworld object instantiation completed
INFO:root:Game version: 1.4.3613 rev621
INFO:root:Game folder: /home/alcatraz/games/RimWorld/game
INFO:root:Configs folder: /home/alcatraz/.config/unity3d/Ludeon Studios/RimWorld by Ludeon Studios/Config
INFO:root:Steam mods folder: 
INFO:root:Local mods folder: /home/alcatraz/games/RimWorld/game/Mods
INFO:root:RimPy Mod Manager v. 1.2.6.29
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:root:Populating mods
INFO:root:Game version: 1.4.3613 rev621
INFO:root:Game folder: /home/alcatraz/games/RimWorld/game
INFO:root:Configs folder: /home/alcatraz/.config/unity3d/Ludeon Studios/RimWorld by Ludeon Studios/Config
INFO:root:Steam mods folder: 
INFO:root:Local mods folder: /home/alcatraz/games/RimWorld/game/Mods
INFO:root:Mods added to QTreeWidgets
CRITICAL:root:Exception
Traceback (most recent call last):
  File "/home/alcatraz/games/RimPy/rimpy.py", line 1815, in checkForUpdates
  File "/home/alcatraz/games/RimPy/multiprocessing/pool.py", line 364, in map
  File "/home/alcatraz/games/RimPy/multiprocessing/pool.py", line 771, in get
  File "/home/alcatraz/games/RimPy/multiprocessing/pool.py", line 125, in worker
  File "/home/alcatraz/games/RimPy/multiprocessing/pool.py", line 48, in mapstar
  File "/home/alcatraz/games/RimPy/rimpy.py", line 1824, in updateStatus
  File "/home/alcatraz/games/RimPy/rmods/steamMod.py", line 27, in __init__
  File "/home/alcatraz/games/RimPy/rmods/steamMod.py", line 40, in populate
  File "/home/alcatraz/games/RimPy/rmods/steamMod.py", line 61, in get_mod_data
ValueError: invalid literal for int() with base 10: 'WhatTheHack-4.0.2'

```

**Comment by v-evets** [comment]
Same error here (js: Uncaught ReferenceError: qt is not defined), no application crash (or crash log) but unable to install / update any mods. 

The downloads appear to be completing successfully (steamcmd output, presence of files in rimworld mod directory, file modification times), but rimpy reports "An issue occured, some mods were not downloaded or updated." [sic], the above qt error is printed to the console, and rimpy is not updated to reflect the new versions.

Attempting to retry the failed mods or any other (manual, not via updater) download results in the same.
Gentoo stable, X11, qt 5.15.8.

**Comment by stasalcatraz** [comment]
> Same error here (js: Uncaught ReferenceError: qt is not defined), no application crash (or crash log) but unable to install / update any mods.

I don't think it's the same error.  in my case it is a segfault on `ValueError: invalid literal for int() with base 10: 'WhatTheHack-4.0.2'`

**Comment by v-evets** [comment]
Fair, and TBH that was a pretty low-effort post on my part, to the first issue with a text match on the console error I was 
getting.

Frankly I'm over this, between the lack of source code and the seemingly constant GNU/Linux issues, RimPy is not worth the hassle any more. In this case it was less effort to hack up a steamcmd updater in shell than try to debug this mess.
I'll probably just switch to rmm at this point, at least it's FOSS. Good luck with your issue.
