### ISSUE TITLE
CRITICAL:root:Exception during opening "Update Log"

### ISSUE THREAD

**Issue by mrclrchtr** [rimpy-custom/RimPy#2]
The application crashes when I click on "Update Log":

````
INFO:root:Rimworld object instantiation completed
INFO:root:Game version: 1.2.2753 rev705
INFO:root:Game folder: C:\Program Files (x86)\Steam\steamapps\common\RimWorld
INFO:root:Configs folder: C:\Users\marce\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config
INFO:root:Steam mods folder: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100
INFO:root:Local mods folder: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods
INFO:root:RimPy Mod Manager v. 1.0.2.9
INFO:qdarkstyle:QSS file sucessfuly loaded.
INFO:qdarkstyle:Found application patches to be applied.
INFO:root:Populating mods
INFO:root:Game version: 1.2.2753 rev705
INFO:root:Game folder: C:\Program Files (x86)\Steam\steamapps\common\RimWorld
INFO:root:Configs folder: C:\Users\marce\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config
INFO:root:Steam mods folder: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100
INFO:root:Local mods folder: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods
INFO:root:Mods added to QListWidgets
CRITICAL:root:Exception
Traceback (most recent call last):
  File "C:\Users\marce\Desktop\RIMPY_~4\rimpy.py", line 1190, in <lambda>
  File "C:\Users\marce\Desktop\RIMPY_~4\rimpy.py", line 3117, in updated
TypeError: arguments did not match any overloaded call:
  fromSecsSinceEpoch(int, spec: Qt.TimeSpec = Qt.LocalTime, offsetSeconds: int = 0): argument 1 has unexpected type 'datetime.datetime'
  fromSecsSinceEpoch(int, QTimeZone): argument 1 has unexpected type 'datetime.datetime'

````

**Comment by rimpy-custom** [comment]
Sorry for a long delay. Should be fixed now. Reopen if not.
