### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'DataFrame'

### ISSUE THREAD

**Issue by gvardian** [rimpy-custom/RimPy#6]
Full stack trace:
- https://justpaste.it/2c6ay

INFO:root:Game version: 1.3.3102 rev827
INFO:root:Game folder: C:\Program Files (x86)\Steam\steamapps\common\RimWorld
INFO:root:Configs folder: C:\Users\pedrom\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config
INFO:root:Steam mods folder: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100
INFO:root:Local mods folder: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods
INFO:root:Mods added to QTreeWidgets
CRITICAL:root:Exception
Traceback (most recent call last):
  File "C:\Users\pedrom\Desktop\RimPy_Windows\rimpy.py", line 4764, in sort
  File "C:\Users\pedrom\Desktop\RimPy_Windows\utils\tsorting.py", line 32, in main
  File "C:\Users\pedrom\Desktop\RimPy_Windows\networkx\algorithms\cycles.py", line 174, in simple_cycles
  File "C:\Users\pedrom\Desktop\RimPy_Windows\networkx\classes\digraph.py", line 318, in __init__
  File "C:\Users\pedrom\Desktop\RimPy_Windows\networkx\convert.py", line 116, in to_networkx_graph
AttributeError: module 'pandas' has no attribute 'DataFrame'

**Comment by gvardian** [comment]
Sorry forgot to add that this happens when sorting the mods.

**Comment by Ozogorgor** [comment]
Every time you update Rimpy (Extracting to disk), delete your former folder containing Rimpy. I.E. Do not replace, extract to a new folder. 
The latest version either changed how pandas were invoked, or removed the dependency altogether (or something else entirely). 

(Always extract, paste or download to new! Never ever use replace. Just forget that replace ever exist).

**Comment by gvardian** [comment]
Thanks for the follow up, really appreciated.

**Comment by rimpy-custom** [comment]
Closing sicne looks fixed
