### ISSUE TITLE
Delete DDS textures on 1.2.6.24 crash

### ISSUE THREAD

**Issue by sdv3** [rimpy-custom/RimPy#60]
I had had lots of textures converted to DDS. I decided to upscale them.
I opened Optimize tex and straight pressed "Delete DDS textures". The operation finished instantly with the message about 0 deleted textures.
I pressed Select All and then Delete DDS textures. Rimpy crashed. The crashlog says,

```
CRITICAL:root:Exception
Traceback (most recent call last):
  File "E:\dist\games\rimworld\RIMPYD~1\rimpy.py", line 1357, in deleteCompressedTextures
  File "E:\dist\games\rimworld\RIMPYD~1\rimpy.py", line 1331, in conversionPrompt
AttributeError: 'builtin_function_or_method' object has no attribute 'append'
```

**Comment by rimpy-custom** [comment]
Will be fixed in next release
