### ISSUE TITLE
cant launch if set color for 235 mods

### ISSUE THREAD

**Issue by DevilPaean** [rimpy-custom/RimPy#90]
this is log file
INFO:root:Building GUI
INFO:root:GUI generated
INFO:root:Rimworld object instantiation
CRITICAL:root:Exception
Traceback (most recent call last):
  File "C:\Users\DP\Desktop\RIMPY_~1\rimpy.py", line 6588, in <module>
  File "C:\Users\DP\Desktop\RIMPY_~1\rimpy.py", line 6574, in main
  File "C:\Users\DP\Desktop\RIMPY_~1\rimpy.py", line 2857, in __init__
  File "C:\Users\DP\Desktop\RIMPY_~1\setup.py", line 16, in __init__
  File "C:\Users\DP\Desktop\RIMPY_~1\setup.py", line 21, in populate
  File "C:\Users\DP\Desktop\RIMPY_~1\setup.py", line 72, in game_version
  File "C:\Users\DP\Desktop\RIMPY_~1\settings.py", line 320, in config_folder
  File "C:\Users\DP\Desktop\RIMPY_~1\configparser.py", line 799, in get
  File "C:\Users\DP\Desktop\RIMPY_~1\configparser.py", line 395, in before_get
  File "C:\Users\DP\Desktop\RIMPY_~1\configparser.py", line 412, in _interpolate_some
AttributeError: 'list' object has no attribute 'find'

and what about add a function that allow us to sort inactive mods by install time? xd

**Comment by rimpy-custom** [comment]
May you upload your config.ini?

**Comment by DevilPaean** [comment]
sorry i deleted......now i'm playing other games......

**Comment by rimpy-custom** [comment]
should be fixed now
