### ISSUE TITLE
Can not check for updates in Ubuntu 22.04

### ISSUE THREAD

**Issue by stasalcatraz** [rimpy-custom/RimPy#91]
RimPy crashes with segmentation fault when clicking "Check for updates" button. When I run RimPy from console, it writes next lines:

$ ./RimPy.sh 
Ошибка открытия URL: https://api.github.com/repos/rimpy-custom/RimPy/releases
Sandboxing disabled by user.
Ошибка открытия URL: https://content-system.gog.com/products/1094900565/os/windows/builds?generation=2
Ошибка открытия URL: https://rimworldwiki.com/wiki/Version/Current_version
1.699837459018454
[241131:241136:0912/205955.609466:ERROR:nss_util.cc(166)] Error initializing NSS with a persistent database (sql:/home/alcatraz/.pki/nssdb): libsoftokn3.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
[241131:241136:0912/205955.609576:ERROR:nss_util.cc(124)] Error initializing NSS without a persistent database: NSS error code: -5925
[241131:241136:0912/205955.609586:FATAL:nss_util.cc(126)] nss_error=-5925, os_error=0
[241099:241099:0912/205955.760997:ERROR:network_service_instance_impl.cc(262)] Network service crashed, restarting service.
js: Uncaught TypeError: Cannot read property 'lastChild' of undefined
js: Uncaught TypeError: Cannot read property 'parentElement' of null 

And when I click "Check for updates":

QCoreApplication::exec: The event loop is already running
Release of profile requested but WebEnginePage still not deleted. Expect troubles !
./RimPy.sh: строка 2: 241099 Ошибка сегментирования                   (стек памяти сброшен на диск) LD_PRELOAD="libpcre.so.3:$LD_PRELOAD" ./RimPy
![Screenshot_20220912_210019](https://user-images.githubusercontent.com/2695146/189725585-f6e8bea1-6091-4d65-b491-405fa21d15d5.png)

**Comment by sweetkid169** [comment]
I am also getting a similar issue, except for the fact that I am on Windows. I have posted the last segment from my log.

`
INFO:root:Rimworld object instantiation completed
INFO:root:Game version: 1.4.3525 rev901
INFO:root:Game folder: 
INFO:root:Configs folder:
INFO:root:Steam mods folder: 
INFO:root:Local mods folder: 
INFO:root:RimPy Mod Manager v. 1.2.6.27
INFO:qdarkstyle:QSS file successfully loaded.
INFO:qdarkstyle:Found version patches to be applied.
INFO:qdarkstyle:Found application patches to be applied.
INFO:root:Populating mods
INFO:root:Game version: 1.4.3525 rev901
INFO:root:Game folder: 
INFO:root:Configs folder:
INFO:root:Steam mods folder: 
INFO:root:Local mods folder: 
INFO:root:Mods added to QTreeWidgets
CRITICAL:root:Exception
Traceback (most recent call last):
  File "G:\Games\PCSIDE~1\RimWorld\RIMPY_~1\rimpy.py", line 1815, in checkForUpdates
  File "G:\Games\PCSIDE~1\RimWorld\RIMPY_~1\multiprocessing\pool.py", line 364, in map
  File "G:\Games\PCSIDE~1\RimWorld\RIMPY_~1\multiprocessing\pool.py", line 771, in get
  File "G:\Games\PCSIDE~1\RimWorld\RIMPY_~1\multiprocessing\pool.py", line 125, in worker
  File "G:\Games\PCSIDE~1\RimWorld\RIMPY_~1\multiprocessing\pool.py", line 48, in mapstar
  File "G:\Games\PCSIDE~1\RimWorld\RIMPY_~1\rimpy.py", line 1824, in updateStatus
  File "G:\Games\PCSIDE~1\RimWorld\RIMPY_~1\rmods\steamMod.py", line 27, in __init__
  File "G:\Games\PCSIDE~1\RimWorld\RIMPY_~1\rmods\steamMod.py", line 40, in populate
  File "G:\Games\PCSIDE~1\RimWorld\RIMPY_~1\rmods\steamMod.py", line 61, in get_mod_data
ValueError: invalid literal for int() with base 10: 'PrepareLanding'`

This also happens when trying to download via the downloader

`Redirecting stderr to 'SteamLibrary\SteamCMD\logs\stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1666144101
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Downloading item 2843483188 ...
ERROR! Download item 2843483188 failed (I/O Operation Failed).Downloading item 746425621 ...
ERROR! Download item 746425621 failed (I/O Operation Failed).Downloading item 730936602 ...`

**Comment by rimpy-custom** [comment]
Try latest prerelease, let me know about results

**Comment by sweetkid169** [comment]
> Try latest prerelease, let me know about results

Does this apply for me as well with Windows, or should I break this out into its own issue?

**Comment by rimpy-custom** [comment]
Closing for now. Reopen if issue wasn't fixed with latest Linux build 1.2.6.28.
